---
# Site Configuration
# ==================

- hosts: zookeepers
  user: root
  roles:
    - { role: common, tags: ["common"] }
    - { role: zookeeper, tags: ["zookeeper"] }

- hosts: codis-dashboard
  user: root
  roles:
    - { role: common, tags: ["common"] }
    - { role: codis-dashboard, tags: ["codis-dashboard"] }

- hosts: codis-proxys
  user: root
  roles:
    - { role: common, tags: ["common"] }
    - { role: codis-proxy, tags: ["codis-proxys"] }

- hosts: codis-servers
  user: root
  roles:
    - { role: common, tags: ["common"] }
    - { role: codis-server, redis_port: 6379, tags: ["codis-servers"] }
    - { role: codis-server, redis_port: 6380, tags: ["codis-servers"] }
