---
# file:roles/codis-server/tasks/main.yml

- name: Init and start server of {{ module }}
  shell: chdir=/opt {{ item }}
  with_items:
    - "mkdir -p {{program_dir}}/{{module}}"
    - "[ -f {{program_dir}}/{{module}}/codis-server ] || ( cd {{program_dir}}/{{module}} && wget -N {{download_url}}/codis/codis.tar.gz && tar -zxf codis.tar.gz )"
    - "mkdir -p {{program_dir}}/{{module}}/etc"
    - "mkdir -p {{opt_log_dir}}/redis"
  ignore_errors: no

- name: Setup {{ module }} cfg file.
  template: src=redis.conf.j2 dest={{ program_dir }}/{{ module }}/etc/redis_{{redis_port}}.conf owner={{deploy_user}} group={{deploy_user} mode=0644

# supervisor
#- name: Setup supervisor conf for {{ module }}
#  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf mode=0644
