---
# file:roles/codis-proxys/tasks/main.yml

- name: Init and start server of {{ module }}
  shell: chdir=/opt {{ item }}
  with_items:
    - "mkdir -p {{program_dir}}/{{module}}"
    - "[ -f {{program_dir}}/{{module}}/codis-proxy ] || ( cd {{program_dir}}/{{module}} && wget -N {{download_url}}/codis/codis.tar.gz && tar -zxf codis.tar.gz )"
  ignore_errors: no

- name: Setup {{ module }} cfg file.
  template: src=config.ini.j2 dest={{ program_dir }}/{{ module }}/config.ini mode=0644

- name: Copy control script to remote host
  copy: src=control dest={{ program_dir }}/{{ module }}/control mode=755

# supervisor
#- name: Setup supervisor conf for {{ module }}
#  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf mode=0644
